spring.application.name=order-service
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Downstream services
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8083}
payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8082}

# Resilience4j Retry - Inventory
resilience4j.retry.instances.inventoryService.max-attempts=3
resilience4j.retry.instances.inventoryService.wait-duration=1s
resilience4j.retry.instances.inventoryService.enable-exponential-backoff=true
resilience4j.retry.instances.inventoryService.exponential-backoff-multiplier=2

resilience4j.timelimiter.instances.inventoryService.timeout-duration=2s

# Resilience4j Circuit Breaker - Inventory
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryService.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventoryService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.inventoryService.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.inventoryService.automatic-transition-from-open-to-half-open-enabled=true

# Resilience4j Retry - Payment
resilience4j.retry.instances.paymentService.max-attempts=3
resilience4j.retry.instances.paymentService.wait-duration=1s
resilience4j.retry.instances.paymentService.enable-exponential-backoff=true
resilience4j.retry.instances.paymentService.exponential-backoff-multiplier=2


# Resilience4j Circuit Breaker - Payment
resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true

# Resilience4j Bulkhead - Inventory
resilience4j.bulkhead.instances.inventoryService.max-concurrent-calls=5
resilience4j.bulkhead.instances.inventoryService.max-wait-duration=0

# Resilience4j Bulkhead - Payment
resilience4j.bulkhead.instances.paymentService.max-concurrent-calls=5
resilience4j.bulkhead.instances.paymentService.max-wait-duration=0

# Resilience4j Rate Limiter - Inventory
resilience4j.ratelimiter.instances.inventoryService.limit-for-period=10
resilience4j.ratelimiter.instances.inventoryService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.inventoryService.timeout-duration=0

# Resilience4j Rate Limiter - Payment
resilience4j.ratelimiter.instances.paymentService.limit-for-period=10
resilience4j.ratelimiter.instances.paymentService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.paymentService.timeout-duration=0

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.kafka=DEBUG